project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
      - text: "Hands-on Exercise 0"
        href: Hands-on_Exercise/Hands-on_Exercise00/Hands-on_E00.html
      - text: "Hands-on Exercise 1"
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: custom.css
    toc: true

editor: visual

